name: Build XXMI Launcher

on:
  push:
    branches: [ CaveRabbit-Experiments ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ${{ env.LOCALAPPDATA }}\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Nuitka + dependencies
      run: |
        pip install -r requirements.txt
        pip install ordered-set
        pip install zstandard
        pip install tk

    - name: Build XXMI Launcher with Nuitka
      run: |
        py -m nuitka src/xxmi_launcher/app.py --standalone --enable-plugin=tk-inter --windows-company-name="XXMI" --windows-product-name="XXMI Launcher" --windows-file-version="9.9.9" --windows-product-version="9.9.9" --windows-uac-admin --windows-console-mode=disable

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: xxmi-launcher-build
        path: app.dist
