name: Build XXMI Launcher

on:
  push:
    branches: [ CaveRabbit-Experiments ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Nuitka + dependencies
      run: |
        pip install nuitka
        pip install -r requirements.txt

    - name: Install ccache
      run: choco install ccache -y

    - name: Build XXMI Launcher with Nuitka
      run: nuitka src/xxmi_launcher/app.py --output-filename="XXMI Launcher.exe" --standalone --enable-ccache --clang --lto=no --jobs=auto --enable-plugin=tk-inter --include-data-dir=Resources=Resources --windows-product-name="XXMI Launcher" --windows-uac-admin --windows-console-mode=disable --assume-yes-for-downloads

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: xxmi-launcher-build
        path: app.dist
