name: Build XXMI Launcher

on:
  push:
    branches: [ CaveRabbit-Experiments ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Cache pip dependencies
      id: cache-pip
      uses: actions/cache@v4
      with:
        path: C:\Users\runneradmin\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Nuitka + dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade nuitka
        pip install ordered-set
        pip install zstandard
        pip install tk

    - name: Build XXMI Launcher with Nuitka
      run: |
        nuitka src/xxmi_launcher/app.py --standalone --enable-plugin=tk-inter  --windows-company-name="XXMI" --windows-product-name="XXMI Launcher - Rabbit Custom" --windows-file-version="2.1.9" --windows-product-version="2.1.9" --windows-uac-admin --windows-console-mode=disable --assume-yes-for-downloads --output-filename="XXMI Launcher.exe"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: xxmi-launcher
        path: app.dist/**
